version: 2
jobs:
   build:
     docker:
       - image: koppor/texlive
     steps:
       - checkout
       - run: pdflatex demo.tex
       - run: cd tests && pdflatex TEST_english_oneside.tex
       - run: cd tests && pdflatex TEST_english_oneside_no_number.tex
       - run: cd tests && pdflatex TEST_english_twoside.tex
       - run: cd tests && pdflatex TEST_german_oneside.tex
       - run: cd tests && pdflatex TEST_german_twoside.tex
       - run: mkdir build && cp README.md tests/*.pdf .github/_config.yml demo.pdf build/
       - run: if [ "$CIRCLE_BRANCH" == "master" ]; then .circleci/deploy-ghpages.sh build/; fi
