version: 2
jobs:
   build:
     docker:
       - image: koppor/texlive
     steps:
       - checkout
       - run: cd tests && pdflatex TEST_english_oneside.tex
       - run: cd tests && pdflatex TEST_english_oneside_no_number.tex
       - run: cd tests && pdflatex TEST_english_twoside.tex
       - run: cd tests && pdflatex TEST_german_oneside.tex
       - run: cd tests && pdflatex TEST_german_twoside.tex
       - run: mkdir build && cp README.md tests/*.pdf .github/_config.yml build/
       - run: .circleci/deploy-ghpages.sh build/
